version: '3.9'

networks:    
    intranet:
        name: intranet

services:
    aliceChat:
        image: node:16-buster
        container_name: aliceChat
        working_dir: /home/aliceChat/
        command: sh -c 'npm run start:aliceRoom'
        volumes:
            - ./:/home/aliceChat/        
        networks:
            - intranet
            
    bobChat:
        image: node:16-buster
        container_name: bobChat
        working_dir: /home/bobChat/
        command: sh -c 'npm run start:bobRoom'
        volumes:
            - ./:/home/bobChat/        
        networks:
            - intranet